apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: sjason
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/sjason-harbor-project/app@sha256:6435cb7ee41391651dbc40a8781952246dbff4771eb145f9589ad6c646b8138f
        ports:
        - containerPort: 5000
